// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnst0yfkaXOGkFgmTxm1bt0tV-GZtdXhQ',
    appId: '1:322546581482:web:a7f320c41cb31880d5bc93',
    messagingSenderId: '322546581482',
    projectId: 'naarinivesh',
    authDomain: 'naarinivesh.firebaseapp.com',
    storageBucket: 'naarinivesh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEMZU6TWb2-qfhJ5Ytm4mY9SSZ4DwFcC8',
    appId: '1:322546581482:android:a01ebcdd3c9cb0b3d5bc93',
    messagingSenderId: '322546581482',
    projectId: 'naarinivesh',
    storageBucket: 'naarinivesh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDvA8VxKZczYPl_Yn5BN3ua96ch0Y1f4s',
    appId: '1:322546581482:ios:e026cea71bfd5d75d5bc93',
    messagingSenderId: '322546581482',
    projectId: 'naarinivesh',
    storageBucket: 'naarinivesh.firebasestorage.app',
    iosBundleId: 'com.example.naarinivesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDvA8VxKZczYPl_Yn5BN3ua96ch0Y1f4s',
    appId: '1:322546581482:ios:e026cea71bfd5d75d5bc93',
    messagingSenderId: '322546581482',
    projectId: 'naarinivesh',
    storageBucket: 'naarinivesh.firebasestorage.app',
    iosBundleId: 'com.example.naarinivesh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnst0yfkaXOGkFgmTxm1bt0tV-GZtdXhQ',
    appId: '1:322546581482:web:8ad9b4932d65fbf1d5bc93',
    messagingSenderId: '322546581482',
    projectId: 'naarinivesh',
    authDomain: 'naarinivesh.firebaseapp.com',
    storageBucket: 'naarinivesh.firebasestorage.app',
  );

}