name: naarinivesh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.2
  animated_text_kit: ^4.2.2
  lottie: ^2.3.2
  card_swiper: ^3.0.1
  confetti: ^0.6.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/